### ISSUE TITLE
Pillow was not installing

### ISSUE THREAD

**Issue by learntoswim** [zayamatias/retroscraper-rpie#1]
I was running into this problem: https://github.com/python-pillow/Pillow/issues/4257

To fix it, I had to run `sudo apt install python3-dev` to fix this.

Maybe it's worth adding that as a requirement for others.

**Comment by zayamatias** [comment]
Hey thanks! Will check this. Can you tell me which was your setup? Is it the original retropie distribution or was retropie installed on top of raspberry os?

**Comment by learntoswim** [comment]
Original retropie distribution. I had updated all that I could think of prior.

**Comment by zayamatias** [comment]
Thanks for that, very strange. I didn't have that issue, but I must admit that I tried so many things (even from fresh installation several times) that I might just have skipped that one. I've added it to the readme in case someone also runs into the same issue. Thanks a lot. 
Taking the opportunity, how do you feel about the general usage of the scraper? Anything that can be improved.
Thanks!

**Comment by learntoswim** [comment]
Asides from the little hiccup, it worked flawlessly, super great! I love seeing the videos and details. Great job.

**Comment by zayamatias** [comment]
Added remarks on README page fro people having the same issue.
